### ISSUE TITLE
Wrappers for bool, int, and float

### ISSUE THREAD

**Issue by angelawang24** [chitalian/a1-part2#7]
Could you add wrappers for other types (bool, int, float) in array, tests for that, and remove your code implementation

**Comment by chitalian** [comment]
These are two separate issues: 

## 1 Wrappers

Could you explains a bit more on how you want us to wrap?

[Edit] - We can create 3 classes that inherit from Object called (Boolean, Integer, FloatingPoint) and add tests for those if that makes sense?

## 2 Code implementation removal (done)

**Comment by angelawang24** [comment]
Yeah that would be great
